---
version: '3.7'

volumes:
  pmm-server-data:

services:
  pmm-server:
    image: ${PMM_SERVER_IMAGE:-perconalab/pmm-server:dev-latest}
    container_name: pmm-server
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PMM_DEBUG=1
      - PMM_ENABLE_ACCESS_CONTROL=1
      - GF_AUTH_OAUTH_ALLOW_INSECURE_EMAIL_LOOKUP=1
      - PERCONA_PORTAL_URL=https://portal-dev.percona.com
      - PMM_DEV_PERCONA_PLATFORM_PUBLIC_KEY=RWTg+ZmCCjt7O8eWeAmTLAqW+1ozUbpRSKSwNTmO+exlS5KEIPYWuYdX
      - PMM_DEV_PERCONA_PLATFORM_ADDRESS=https://check-dev.percona.com:443
      - PMM_DEV_TELEMETRY_INTERVAL=10s
      - PMM_DEV_TELEMETRY_RETRY_BACKOFF=10s
    volumes:
      - pmm-server-data:/srv
